# Form implementation generated from reading ui file 'interfata_principala.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 979)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.startLine.setObjectName("startLine")
        self.verticalLayout.addWidget(self.startLine)
        self.destLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.destLine.setObjectName("destLine")
        self.verticalLayout.addWidget(self.destLine)
        self.calcButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calcButton.setObjectName("calcButton")
        self.verticalLayout.addWidget(self.calcButton)
        self.mapLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.mapLabel.setObjectName("mapLabel")
        self.verticalLayout.addWidget(self.mapLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1332, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startLine.setPlaceholderText(_translate("MainWindow", "Plecare"))
        self.destLine.setPlaceholderText(_translate("MainWindow", "Sosire"))
        self.calcButton.setText(_translate("MainWindow", "Calculeaza ruta"))
        self.mapLabel.setText(_translate("MainWindow", "Harta va aparea aici"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
